const data ={
    products:[
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 700,
            brand: 'Easy',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'A brand new shirt',
            isFeatured: true,
            banner: 'images/banner1.jpg',
        },
        {
            name: 'Fit Shirt',
            slug: 'fit-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 900,
            brand: 'shoylpik',
            rating: 3.5,
            numReviews: 10,
            countInStock: 10,
            description: 'A brand new shirt',
            isFeatured: true,
            banner: 'images/banner2.jpg',
        },
        {
            name: 'Slim Shirt',
            slug: 'slim-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 500,
            brand: 'Gents Smart',
            rating: 4.5,
            numReviews: 3,
            countInStock: 15,
            description: 'A brand new shirt',
            isFeatured: true,
        },
        {
            name: 'Golf Pants',
            slug: 'golf-pants',
            category: 'Pants',
            image: '/images/pant1.jpg',
            price: 100,
            brand: 'Oliver',
            rating: 2.9,
            numReviews: 13,
            countInStock: 20,
            description: 'A brand new pant',
            isFeatured: true,
        },
        {
            name: 'Fit Pants',
            slug: 'fit-pants',
            category: 'Pants',
            image: '/images/pant2.jpg',
            price: 300,
            brand: 'Zara',
            rating: 3.5,
            numReviews: 7,
            countInStock: 20,
            description: 'A populer pant',
            isFeatured: true,
        },
        {
            name: 'Classic Pants',
            slug: 'classic-pants',
            category: 'Pants',
            image: '/images/pant3.jpg',
            price: 300,
            brand: 'Casely',
            rating: 2.4,
            numReviews: 14,
            countInStock: 20,
            description: 'A populer pant',
            isFeatured: true,
        },
    ]
}

export default data;